### PR TITLE
Configure tasks lazily

### LINKED ISSUE #88: Multiple flavours wrong pull directory
I have two flavours of app: main and chain. Main has applicationId = "com.domain.app" and Chain has applicationId = "com.domain.app.chain" . When i try to pull tapes it pulls from /sdcard/okreplay/tapes/com.domain.app.chain.test/ and when i comment Chain flavour in gradle it pulls from /sdcard/okreplay/tapes/com.domain.app.test/ like it should be. Also folder on sd card is named com.domain.app.chain.test no matter if Chain is commented or not in gradle. Does this library has support for multiple flavours?

### PR DESCRIPTION
**Pull request by technoir42**
This fixes an issue where applying OkReplay plugin would cause all tasks in the project to be configured eagerly.
Also fixes #88 and #91.

### CODE REVIEW

File: okreplay-gradle-plugin/src/test/testProject/android/buildScriptFixtures/gradle.properties [hunk 1]
```diff
@@ -0,0 +1 @@
+android.useAndroidX=true
```
Comment (technoir42) [inline okreplay-gradle-plugin/src/test/testProject/android/buildScriptFixtures/gradle.properties]: This property is required starting with AGP 3.6

File: okreplay-gradle-plugin/src/main/kotlin/okreplay/OkReplayPlugin.kt [hunk 2]
```diff
@@ -1,77 +1,67 @@
...
 
   override fun apply(project: Project) {
-    this.project = project
-    if (project.plugins.hasPlugin(AppPlugin::class.java)
-        || project.plugins.hasPlugin(LibraryPlugin::class.java)) {
-      applyPlugin()
-    } else {
-      throw IllegalArgumentException("OkReplay plugin couldn't be applied. "
-          + "The Android or Library plugin must be configured first.")
+    project.plugins.withId("com.android.application") {
```
Comment (rossbacher) [inline okreplay-gradle-plugin/src/main/kotlin/okreplay/OkReplayPlugin.kt]: why not  like this?
```kotlin
withType(AppPlugin::class.java)
```

Comment (technoir42) [reply okreplay-gradle-plugin/src/main/kotlin/okreplay/OkReplayPlugin.kt]: In general I prefer using ids because they are documented but since we are hard-coding extension types anyway I see that there is not much point in this.

**Comment by rossbacher** [comment]
Thank you!
